jobs:
  - name: job-upload-to-s3
    public: true
    plan:
      - task: upload-to-s3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [This is a first try from git]
